#!/usr/bin/python3
import argparse
parser = argparse.ArgumentParser()
parser.add_argument("string")
args = parser.parse_args()

for chrs in args.string:
    print(hex(ord(chrs))[2:].ljust(2, "0"), end=" ")
